name: Create Konektor Release On Demand

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Enter the existing Git tag to release (e.g., v1.1.0)"
        required: true
        type: string

jobs:
  build-and-release:
    name: "[${{ inputs.version_tag }}] Build Konektor, create installer and release it (public)"
    uses: ./.github/workflows/release.yml
    with:
      version_tag: ${{ inputs.version_tag }}
    secrets:
      PAT: ${{ secrets.PAT }}
